### Create a Phone
POST http://localhost:5555/api/phones
Content-Type: application/json

{
  "model": "iPhone 15",
  "year": 2023,
  "ram": 8,
  "processor": "A16 Bionic",
  "screenSize": 6.1,
  "hasNFC": true,
  "image": "iphone_15.jpg",
  "brandId": 1
}

### Get All Phones (with pagination)
GET http://localhost:5555/api/phones?page=1&results=5

### Get a Phone by ID
GET http://localhost:5555/api/phones/1

### Update a Phone
PATCH http://localhost:5555/api/phones/1
Content-Type: application/json

{
  "ram": 12,
  "processor": "A17 Bionic"
}

### Update or Create a Phone
PUT http://localhost:5555/api/phones/1
Content-Type: application/json

{
  "model": "iPhone 16",
  "year": 2024,
  "ram": 12,
  "processor": "A17 Bionic",
  "screenSize": 6.3,
  "hasNFC": true,
  "image": "iphone_16.jpg"
}

### Delete a Phone
DELETE http://localhost:5555/api/phones/1

### Update Phone Image
#PATCH http://localhost:5555/api/phones/1/image
#Content-Type: multipart/form-data
#
#phoneImage=
